### ISSUE TITLE
Perform tech review of timeseries forecasting tools 

### ISSUE THREAD

**Issue by chintanp** [demand-consults/demand_acep#18]
* Classical approaches
* Machine learning approaches

**Comment by reconjohn** [comment]
As an evolution of artificial neural network (ANN)-based prediction methods, deep learning techniques are expected to increase the prediction accuracy by allowing higher levels of abstraction. In this paper, we investigate two newly developed stochastic models for time series prediction of energy consumption, namely Conditional Restricted Boltzmann Machine (CRBM) and Factored Conditional Restricted Boltzmann Machine (FCRBM). The assessment is made on a benchmark dataset consisting of almost four years of one minute resolution electric power consumption data collected from an individual residential customer. The results show that for the energy prediction problem solved here, FCRBM outperforms ANN, Support Vector Machine (SVM), Recurrent Neural Networks (RNN) and CRBM.

https://www-sciencedirect-com.offcampus.lib.washington.edu/science/article/pii/S2352467716000163

![image](https://user-images.githubusercontent.com/10944497/56261383-a832c480-608f-11e9-8f8a-374024c5b5cf.png)

**Comment by reconjohn** [comment]
The empirical studies conducted and reported in this article show that deep learning-based algorithms such as LSTM outperform traditional-based algorithms such as ARIMA model. More specifically, the average reduction in error rates obtained by LSTM is between 84 - 87 percent when compared to ARIMA indicating the superiority of LSTM to ARIMA. Furthermore, it was noticed that the number of training times, known as "epoch" in deep learning, has no effect on the performance of the trained forecast model and it exhibits a truly random behavior.

https://arxiv.org/ftp/arxiv/papers/1803/1803.06386.pdf

**Comment by reconjohn** [comment]
ARIMA vs. RNN 

" If you’ve got the time to read a ~20 page research paper that covers this exact topic (ARIMA vs. RNNs) as it applies to forecasting aviation time series - please check out this survey paper that I’ve written and posted on GitHub. If you want to dig deeper, feel free to explore the Jupyter Notebooks and data that I scraped from the US DOT and included in the repo. It was a lot of work and I’ve licensed it so that anyone can do anything with it now. It will save you A LOT of time if you are trying to spin up RNNs for a time series problem on your own. If you want to go even further, check out this repo of the first place solution to a Kaggle competition on time series that took place last year. The winner’s solution involved a much more sophisticated RNN architecture than the one I used for my project, and he was certainly awarded handsomely for it. It was the most important inspiration for my work so I’m happy to refer it researchers and engineers interested in these kinds of problems."

https://github.com/shellshock1911/Sky-Cast-Capstone/tree/master/notebooks

**Comment by reconjohn** [comment]
**ARIMA for power consumption of a household** 

It is a multivariate series comprised of seven variables (besides the date and time); they are:

- global_active_power: The total active power consumed by the household (kilowatts).
- global_reactive_power: The total reactive power consumed by the household (kilowatts).
- voltage: Average voltage (volts).
- global_intensity: Average current intensity (amps).
- sub_metering_1: Active energy for kitchen (watt-hours of active energy).
- sub_metering_2: Active energy for laundry (watt-hours of active energy).
- sub_metering_3: Active energy for climate control systems (watt-hours of active energy).

https://machinelearningmastery.com/how-to-develop-an-autoregression-forecast-model-for-household-electricity-consumption/

**Comment by chintanp** [comment]
ARIMA was used for [load forecasting](https://demand-acep.readthedocs.io/en/latest/forecast.html#forecast-based-on-month) and GAN was used for [load synthesis](https://demand-acep.readthedocs.io/en/latest/load_synthesis.html).
